### PR TITLE
ISSUE-123 - Send keep alive messages at periodic interval

### LINKED ISSUE #123: Subscriptions are missing keepalives
Been meaning to post this for a while after discussing it in the chat. I'd been having issues with the websocket connection closing and reopening - thanks to apollo reconnect - every ~50 seconds and not being able to determine why. After doing some research it seems that norm is that the server sends a keepalive.

https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

This isn't majorly important at the moment and shouldn't be a big change so I'll try to look into it at some point in the future if no one else does, but it might be a while before I can get to it. Unit tests for subscriptions would be a big help in making that something that's safer to work on without fear of breaking things.

For anyone who comes across this issue in the meantime I've been able to implement a workaround on the apollo client side using a websocket link:

```
const subscriptionClient = new SubscriptionClient(this.wsdomain, {
	reconnect: true,
	lazy: true,
        options: {
		reconnect: true,
		lazy: true,
//		... other options ...
	}
});

setInterval(() => {
	if (subscriptionClient.status === 1) {
		subscriptionClient.client.send('{"type":"ka"}');
	 }
}, 40000);
const wsLink = new WebSocketLink(subscriptionClient);
```

Thanks!

### PR DESCRIPTION
**Pull request by Maximilien-R**
Closes #123.

### CODE REVIEW

**Comment by abusi** [comment]
@Maximilien-R very nice man ! Thanks
Don't forget changelog/doc :)

**Comment by Maximilien-R** [comment]
I'm waiting for a feedback from @daveoconnor if it does fix his issue, then I''ll update both changelogs and documentation 👍

**Comment by Maximilien-R** [comment]
@abusi, it should be good now, I updated the changelogs and the package version.

Regarding the documentation, it's on the `tartiflette` repository. There is no documentation on the `tartiflette-aiohttp` repository itself.

**Review by abusi — APPROVED** [review]

**Comment by abusi** [comment]
Thanks @Maximilien-R

**Pull request merged**
